### ISSUE TITLE
How do you add a font?

### ISSUE THREAD

**Issue by jzucadi** [sandrina-p/essential-webpack-boilerplate#3]
After looking over a half dozen guides I still can't get webpack to load my fonts. Is there any chance someone can post an example of loading a local font? 

Using this loader in my config.js :
```
{
                test: /\.(ttf|eot|woff|woff2)$/,
                loader: 'file-loader',
                options: {
                    name: 'fonts/[name].[ext]',
                },
            },

```

and in my CSS:

```
@font-face {
  font-family: 'Myriad';
  src: url('../MPR.ttf') format('ttf'),
}
```

Really appreciate any insight, trying to avoid rebuilding my entire project in gulp just to add a font.

**Comment by sandrina-p** [comment]
I can take a look into it tomorrow 🙂

**Comment by jzucadi** [comment]
thanks! Really dig the starter kit, thanks for posting it

**Comment by jzucadi** [comment]
Hey, I'm sorry to bother you with something so trivial I figured out what I was doing wrong. I made a separate css file to list my fonts and then imported that file into my index.js. Works now.

**Comment by sandrina-p** [comment]
Hey @jzucadi, glad you found a solution by yourself! 😄 

I updated the project and now you can load not only `fonts` but also `images` on html or css without having to import them individually in js files

👀  You can can check it live at `//localhost:3001`

#### Load images
```html
<img src="media/cat.gif" alt="A cat hiding in a small aquarium bowl">
```
or 
```css
.foo {
    background-image: url('../media/cat.gif');
}
```

#### Load fonts
```css
/* styles/fonts/index.css */
@font-face {
  font-family: AldoTheApache;
  font-weight: 100;
  src: url('AldotheApache.ttf');
}

/* styles/index.css */
.foo {
  font-family: AldoTheApache;
}
```

---

Hope to help you! 😎
